### PR TITLE
No default exports

### PR DESCRIPTION
**Pull request by carlhoerberg**
So that all classes can be imported in other projects, espeically useful
for TypeScript projects which want's to declare return classes from
methods.

Will require a major version bump as it's a very breaking change.

Addressing part of #21

### CODE REVIEW

**Comment by jonaskello** [comment]
Thanks for looking into this issue!

I published this PR as a package at @jonaskello-forks/amqp-client, v2.0.0. I then tried it out in a regular nodejs project. With the current changes in this PR it is possible to do:

```ts
import { AMQPClient } from "@jonaskello-forks/amqp-client";
import { AMQPWebSocketClient } from "@jonaskello-forks/amqp-client";
```

However, none of the other classes works to import, eg. this is still not possible:

```ts
import { AMQPChannel } from "@jonaskello-forks/amqp-client";
```

I do agree that default exports are not worth the trouble so it is probably better to just get rid of them altogheter like is done in this PR. However, since all default exports are already re-exported as named exports in [the index.ts file here](https://github.com/cloudamqp/amqp-client.js/blob/main/src/index.ts#L9) I don't think the changes are necessary to support named imports.

There are many ways to publish packages, and a myriad of tools to help you do it. So I can of course not make any suggestions without being opinionated :-). My oppionon is to make it as simple as possible. So I would suggest just using the the typescript compiler `tsc`.

Publish the full output from `tsc` in the `./lib` folder as commonjs modules (`*.js`, `*.js.map`, `*.d.ts`, and `*.d.ts.map` files). In `package.json`, set the `main` field to `./lib/index.js` and the `types` field to `./lib/index.d.ts`.

With this done, all javascript/typescript nodejs projects should be able to consume this package without any problems. Any javascript/typescript web projects that run their own bundler like webpack/rollup/parcel/snowpack/vitejs etc. should also be able to consume it without any problems.

In addition the package could also continue to provide pre-bundled files in `./dist` for projects that wants to copy the file to a CDN or something like that. This could be done using rollup like today, but without any extra plugins for typescript. Instead just have rollup bundle the javascript files that `tsc` built from `./lib` to `./dist`. No type files are needed in `./dist` as typescript projects will work directly from `./lib`.

The `browser` field in `package.json` IMO can be removed if a full `./lib` folder is provided.

I see in `package.json` that this package support the new `exports` field. This is of course nice but IMO not really necessary. I think at this point, getting the package to work proper in a traditional way would be more interesting than supporting this new field. Typescript has still not added support for this field (well they added it and then removed it because it is very complex to get right). For nodejs I think you still need to enable experimental features for this field to be recognized. Once it is possible to consume this package in a traditional way, it would be of course be interesting to explore adding support for this too.

As I said this is just highly oppninated suggestions based on my experience publishing npm packages. My main concern is just being able to consume the package in an idomatic way from typescript/javascript projects for both nodejs and web. Any tooling/solution that achieves that works for me :-).

**Comment by carlhoerberg** [comment]
thank you for your feedback, i've made a number of changes if you would like to try it out.

**Comment by carlhoerberg** [comment]
rollupjs can only roll up mjs/esm modules, not cjs (only with plugins, and even then it gets ugly i think), thus mjs files have to be included in the package. mjs is also required for tree-shaking, in rollup, webpack etc. 

lib/types etc are only names, might be a convention but not a rule, but i now put the tsc output in lib/mjs and lib/cjs respectively, and types in ./types.  

exports.import and exports.require are fully supported since couple of nodejs version back, 12 or 14 i think, and not anything new. many benefits of using it. but cjs is still required for legacy apps that does `require` and not `import`.

removed typescript in rollup config, but then needed to add another plugin for sourcemap to point to the .ts files and not the tsc output files which would be meaningless.

**Comment by jonaskello** [comment]
Thanks for taking the time to make all the the changes :-)

I published the current state of this PR to a package and imported it into [my exmple project](https://github.com/jonaskello/amqp-websockets-example/tree/forked-package201) that uses webpack, typescript, and react.

It works a lot better and the code below builds without problem with `tsc`. So it is now possible to import classes and types in an idomatic way like this:

```ts
import { AMQPWebSocketClient, AMQPChannel } from "@jonaskello-forks/amqp-client";
//
const amqp = new AMQPWebSocketClient(url, "/", "guest", "guest");
//
function View(): JSX.Element {
  const [channel, setChannel] = React.useState<AMQPChannel>();
//

```

However there is one last hurdle. When I run it with webpack-dev-server I get this error in run-time:

```
bundle.js:397 Uncaught ReferenceError: exports is not defined
    at eval (index.js:3:23)
    at Module../node_modules/@jonaskello-forks/amqp-client/lib/cjs/index.js (bundle.js:365:1)
    at __webpack_require__ (bundle.js:394:33)
```

I tracked this down to the `"type": "module"` field in `package.json`. If I remove that field everything works.

I think is what is happening is that `"type": "module"` tells webpack to expect ESM modules. However the `main` field is set to `lib/cjs/index.js` which is a CJS module. So when webpack tries to load the `main` field as an ESM module it encounters `exports` which is not present as a global for ESM modules. Thus webpack says `exports` is undefined.

> exports.import and exports.require are fully supported since couple of nodejs version back

Yes, you're right, I was confusing it with [loaders](https://nodejs.org/api/esm.html#loaders) which is still experimental. Also `tsc` does [not yet suport this](https://github.com/microsoft/TypeScript/issues/33079). Anyway, these fields is definitely the future way of doing things.

Regarding the remaining issue mentioned above I see two ways to solve it:

First solution:
Remove `"type": "module"` from `package.json` to signal that `.js` files [should be treated as CJS](https://nodejs.org/api/packages.html#type).

Second solution:
Remove support for CJS modules altogether. Keep `"type": "module"`, only publish one set of ESM module files to `lib` and set `main` to `lib/index.js`. I I think this would be possible if only nodejs>12 support is needed. Nodejs>12 should respect `"type": "module"` and treat all .js files as ESM modules. Bundlers like webpack etc. also supports `"type": "module"` so that should also work. And `tsc` will only look at the types so it also works. I did a quick test with this approach. In package.json I changed `main` to `lib/mjs/index.js` and removed `exports`. This still works with my webpack example (altough it complained about sourcemaps: `DevTools failed to load source map: Could not load content for webpack://amqp-websockets-example/node_modules/@jonaskello-forks/amqp-client/lib/mjs/index.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME`).

**Comment by carlhoerberg** [comment]
went with solution 3 :bulb: : adding a package.json file with `{"type": "commonjs"}` to lib/cjs/. that should tell node to treat the files in that dir as commonjs files. does that work for webpack too? but ideally i would like webpack to use the esm module.. this docs says it should pick up the `exports` property: https://webpack.js.org/guides/package-exports/

solution 2 isn't very good because users who still uses commonjs won't then be able to use (`require`) the library then, and i think that's still a fairly large population unfortunately. could be overcome by forcing them to use the [dynamic import](https://nodejs.org/docs/latest-v16.x/api/esm.html#import-expressions), but that's a hassle and learning curve. 

More reference: https://nodejs.org/docs/latest-v16.x/api/packages.html#dual-commonjses-module-packages

**Comment by carlhoerberg** [comment]
Tried your example app and my fix solved it, it understands that the files in lib/cjs are commonjs files then.

And to make your app use the esm version of libs you have to change your tsconfig.json with the following: 
```
    "module": "es2015",
    "moduleResolution": "node",
```

then it logs: 
```
modules by path ./node_modules/@jonaskello-forks/amqp-client/lib/mjs/*.js 83.9 KiB 10 modules
```

**Comment by carlhoerberg** [comment]
btw, you can also install package from a git repo without having to publish your own npm package: 

```json
  "dependencies": {
    "cloudamqp/amqp-client": "git://github.com/cloudamqp/amqp-client.js.git#no-default-export",
   }
```

**Comment by jonaskello** [comment]
Yes now it works, thanks :-)

In a perfect world we would only have to worry about ESM modules, but yes, there are a lot of projects still running older stuff. IIRC turning on `"module": "es2015"` in a larger typescript codebase that uses `__dirname` and other CJS specific stuff all over the place is a bit of pain too.

I'll investigate a little bit more why webpack is not picking up the exports field in the example. I guess having it read the ESM modules instead would result in better tree-shaking so that is definitely preferable.

Neat trick to install the package directly from the branch 👍

**Comment by jonaskello** [comment]
Another thing that is not really needed but would be nice if it could be solved is that webpack will now complain like this:

```
ERROR in ./node_modules/@jonaskello-forks/amqp-client/lib/cjs/amqp-socket-client.js 27:25-39
Module not found: Error: Can't resolve 'net' in '/home/jonkel/code/github/jonaskello/amqp-websockets-example/node_modules/@jonaskello-forks/amqp-client/lib/cjs'
 @ ./node_modules/@jonaskello-forks/amqp-client/lib/cjs/index.js 4:30-64
 @ ./src/index.tsx 17:22-62

ERROR in ./node_modules/@jonaskello-forks/amqp-client/lib/cjs/amqp-socket-client.js 28:25-39
Module not found: Error: Can't resolve 'tls' in '/home/jonkel/code/github/jonaskello/amqp-websockets-example/node_modules/@jonaskello-forks/amqp-client/lib/cjs'
 @ ./node_modules/@jonaskello-forks/amqp-client/lib/cjs/index.js 4:30-64
 @ ./src/index.tsx 17:22-62
```

This can be fixed by adding [the line below](https://github.com/jonaskello/amqp-websockets-example/blob/7192ce93fd1eb158814110692d0e53244ed47f53/webpack.config.js#L7) to the webpack config. You can remove that line in the example to see the error.

```js
module.exports = {
  resolve: {
    fallback: { buffer: false, tls: false, net: false },
  },
```

I'm not sure what is the best way to deal with this. I guess it happens because when you import one thing from the index file, you import all files implicitly, including files that have nodejs specific stuff. Perhaps a second index file like `web.js` could be published but it would not import any nodejs stuff. It could then be imported like `@cloudamqp/amqp-client/web`.

For me this is not really important as it can be worked around by the above webpack config. Perhaps it could be dealt with in a separate PR as it would be great to have this PR published as soon as possible.

**Comment by carlhoerberg** [comment]
tried with a subexport (`@cloudamqp/amqp-client/web`, but typescript doesn't support it (as we touched earlier), so resorted to ignoring those via the `browser` property: https://github.com/cloudamqp/amqp-client.js/pull/22/commits/ba520c8edd745e35abbb07d3bf44fe5aa1032035

that seems to fix it, but only if the esm module is used (and thus `"module": "es2015"` in your tsconfig.json is required for it to work).

**Comment by carlhoerberg** [comment]
v2.0.0 is now released with this PR included, thank you for the collaboration!

**Pull request merged**
